stages:
  - prod
  - dev
  - stage
dashboards: true
topics:
  alarm:
    topic: ${self:service}-${self:provider.stage}-alerts-alarm
definitions:
  functionErrors:
    namespace: "AWS/Lambda"
    metric: Errors
    threshold: 100
    statistic: Sum
    period: 60
    evaluationPeriods: 1
    comparisonOperator: GreaterThanOrEqualToThreshold
    treatMissingData: missing
  functionThrottles:
    namespace: "AWS/Lambda"
    metric: Throttles
    threshold: 10
    statistic: Sum
    period: 60
    evaluationPeriods: 1
    comparisonOperator: GreaterThanOrEqualToThreshold
    treatMissingData: missing
alarms:
  - functionErrors
  - functionThrottles
