Parameters:
  EnvType:
    Description: Environment type
    Default: ${self:provider.stage}
    Type: String
Conditions:
  StaticIpEnabled:
    Fn::Or:
      [
        { "Fn::Equals": [{ "Ref": EnvType }, dev] },
        { "Fn::Equals": [{ "Ref": EnvType }, stage] },
        { "Fn::Equals": [{ "Ref": EnvType }, prod] },
      ]

Resources:
  # Step 1: Create a new VPC
  VPCStaticIP:
    Condition: StaticIpEnabled
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.0.0.0/16
      Tags:
        - Key: Name
          Value: ${self:custom.name}-vpc

  # Step 2: Create 2 Subnets
  SubnetPublic:
    Type: AWS::EC2::Subnet
    Condition: StaticIpEnabled
    Properties:
      AvailabilityZone: ${self:custom.region}b
      CidrBlock: 11.0.0.0/24
      Tags:
        - Key: Name
          Value: ${self:custom.name}-public-subnet
      VpcId:
        Ref: VPCStaticIP

  SubnetPrivate:
    Type: AWS::EC2::Subnet
    Condition: StaticIpEnabled
    Properties:
      AvailabilityZone: ${self:custom.region}b
      CidrBlock: 11.0.1.0/24
      Tags:
        - Key: Name
          Value: ${self:custom.name}-private-subnet
      VpcId:
        Ref: VPCStaticIP

  # Step 3: Create an Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: StaticIpEnabled
    Properties:
      Tags:
        - Key: Name
          Value: ${self:custom.name}-igw

  # Attach Internet Gateway to VPC
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: StaticIpEnabled
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPCStaticIP

  # Step 4: Create a public Route Table and Assign it to our public route
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Condition: StaticIpEnabled
    Properties:
      VpcId:
        Ref: VPCStaticIP
      Tags:
        - Key: Name
          Value: ${self:custom.name}-public-route

  RoutePublic:
    Type: AWS::EC2::Route
    Condition: StaticIpEnabled
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTablePublic

  SubnetRouteTableAssociationPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: StaticIpEnabled
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: SubnetPublic

  # Step 5: Create a NAT Gateway
  # Before creating NAT Gateway, we need to create Elastic IP with vpc scope
  EIP:
    Type: AWS::EC2::EIP
    Condition: StaticIpEnabled
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Condition: StaticIpEnabled
    Properties:
      Tags:
        - Key: Name
          Value: ${self:custom.name}-NatGateway
      AllocationId:
        Fn::GetAtt: [EIP, AllocationId]
      SubnetId:
        Ref: SubnetPublic

  # In tutorial NAT Gateway is attached as default route 0.0.0.0/0 in main Route Table.
  # Main Route Table is created implicitely during VPC creation and CloudFormation
  # has no access to its ID. To overcome this limitation we create additional Route Table.
  RouteTablePrivate:
    Type: AWS::EC2::RouteTable
    Condition: StaticIpEnabled
    Properties:
      VpcId:
        Ref: VPCStaticIP
      Tags:
        - Key: Name
          Value: ${self:custom.name}-private-route

  RoutePrivate:
    Type: AWS::EC2::Route
    Condition: StaticIpEnabled
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NatGateway
      RouteTableId:
        Ref: RouteTablePrivate

  SubnetRouteTableMainAssociationPrivate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: StaticIpEnabled
    Properties:
      RouteTableId:
        Ref: RouteTablePrivate
      SubnetId:
        Ref: SubnetPrivate
