service:
  name: xxx-db # TODO: change xxx to your name
  publish: false

frameworkVersion: "=1.42.3"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'temp'}
  region: "${file(../serverless.yml):provider.region}"
  memorySize: ${self:custom.env.lambdaMemorySize.${self:provider.stage}, self:custom.env.lambdaMemorySize.default} # optional, in MB, default is 1024
  timeout: ${self:custom.env.lambdaTimeout.${self:provider.stage}, self:custom.env.lambdaTimeout.default} # optional, in seconds, default is 6
  versionFunctions: false
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    name: xxx-${self:provider.stage}-deploys # TODO: change xxx to your name
    serverSideEncryption: AES256
  environment:
    BASE_URL:
      Fn::ImportValue: "ApiGatewayBaseUrl-${file(../serverless.yml):service.name}-${self:provider.stage}"

package:
  individually: true
  excludeDevDependencies: true

functions: ${file(resources/lambda-functions.yml)}

resources: ${file(resources/resources.yml)}

plugins:
  - serverless-deployment-bucket
  - serverless-webpack

custom:
  env:
    lambdaMemorySize: "${file(../serverless.yml):custom.env.lambdaMemorySize}"
    lambdaTimeout: "${file(../serverless.yml):custom.env.lambdaTimeout}"
    accountId: "${file(../serverless.yml):custom.env.accountId}"
    ReadCapacityUnits:
      prod: 5
      dev: 2
      stage: 2
      default: 1
    WriteCapacityUnits:
      prod: 5
      dev: 2
      stage: 2
      default: 1
    ReadCapacityMaxUnits:
      prod: 100
      dev: 40
      stage: 40
      default: 2
    WriteCapacityMaxUnits:
      prod: 100
      dev: 20
      stage: 20
      default: 2
  name: "${self:service}-${self:provider.stage}"
  lambdaName: "${file(../serverless.yml):service.name}-${self:provider.stage}"
  lambdaBatchSize: 20
  # `Trying to populate non string value into a string for variable` if i get region from self:provider.region
  region: "${file(../serverless.yml):custom.region}"
  accountId: 793509417022
  webpack:
    webpackConfig: ../webpack.config.js
    includeModules:
      packagePath: ../package.json
      forceInclude:
        - source-map-support
      forceExclude:
        - aws-sdk
